name: Pipeline with SonarQube, Trivy, and Docker Hub

on:
  push:
  pull_request:

env:
  BRANCH_NAME: ${{ github.ref_name }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  IMAGE_NAME: ${{ github.repository }}
  SHA: ${{ github.sha }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/go/bin v1.59.0
      - name: Add golangci-lint to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Lint Go code
        working-directory: ./
        run: golangci-lint run

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Run Go tests
        working-directory: ./
        run: go test ./... -v

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    # only runs on dev and main
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        id: extract_branch
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME//\//-}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.SHA }}
            ${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}
